export const transactions = [
  {
    id: 1,
    label: "Netflix",
    category: "Entertainment",
    amount: -15.99,
    emoji: "🎬",
    color: "#ffd8ce",
  },
  {
    id: 2,
    label: "Salary",
    category: "Income",
    amount: 3500.0,
    emoji: "💼",
    color: "#d4f5e8",
  },
  {
    id: 3,
    label: "Grocery Store",
    category: "Food",
    amount: -84.5,
    emoji: "🛒",
    color: "#fff3cc",
  },
  {
    id: 4,
    label: "Uber",
    category: "Transport",
    amount: -12.3,
    emoji: "🚗",
    color: "#cce9ff",
  },
  {
    id: 5,
    label: "Coffee Shop",
    category: "Food",
    amount: -6.75,
    emoji: "☕",
    color: "#ffd6ec",
  },
  {
    id: 6,
    label: "Amazon",
    category: "Shopping",
    amount: -59.99,
    emoji: "📦",
    color: "#fff3cc",
  },
  // {
  //   id: 7,
  //   label: "Gym",
  //   category: "Health",
  //   amount: -30.0,
  //   emoji: "🏋️",
  //   color: "#d4f5e8",
  // },
];
